### ISSUE TITLE
Error: describe('test generation with inference', function () { ^ ReferenceError: describe is not defined

### ISSUE THREAD

**Issue by ujjwal08** [earldouglas/swagger-test#8]
I downloaded this project and tried to run it, It is showing error that-

describe('test generation with inference', function () {
^
ReferenceError: describe is not defined

Below is the screeshot of my console output: 

![selection_007](https://cloud.githubusercontent.com/assets/25145383/21980896/eacde3ee-dc0a-11e6-9ed0-aa5a657eeed7.png)

how to resolve this error?

**Comment by earldouglas** [comment]
The `describe` function comes from Mocha, which is included in the [module's "development" dependencies][1].  You can use npm to both install them and bring them in scope for testing:

```
[james@X200s:~/code/swagger-test]$ npm install
```

Here, you should see a bunch of output from downloading and building each dependency.  The results end up in the *./node_modules* directory.

```
[james@X200s:~/code/swagger-test]$ npm test

> swagger-test@0.5.1 test /home/james/code/swagger-test
> mocha

  test generation with inference
    ✓ should contain three test cases 
    ✓ should first test GET /pets 
    ✓ should next test GET /pets/fido4 
    ✓ should next test GET /pets/fido7 


  4 passing (22ms)
```

[1]: https://github.com/earldouglas/swagger-test/blob/c05852d/package.json#L36

**Comment by ujjwal08** [comment]
@earldouglas thanks, It worked. :+1:

**Comment by earldouglas** [comment]
Great!
